@echo off
REM Auto-generated by packages/fw-plugins/build/lib/pack-mcpb.ts.
REM
REM Fireweave MCP launcher (Windows). Runs the windows-x64 binary, fetching
REM + verifying + extracting from the per-OS MCPB on first launch if not
REM already present in bin\.
REM
REM Customer-side prereq: PowerShell 5.1+ (ships with Windows 10+). The
REM Unix launcher.sh is the primary; this is the Windows fallback.

setlocal enabledelayedexpansion

set "DIR=%~dp0"
if "%DIR:~-1%"=="\" set "DIR=%DIR:~0,-1%"
set "BIN_DIR=%DIR%\bin"
set "URLS_JSON=%DIR%\urls.json"
set "BIN_NAME=server-windows-x64.exe"
set "BIN_PATH=%BIN_DIR%\%BIN_NAME%"

REM Fast path: binary already cached.
if exist "%BIN_PATH%" (
  "%BIN_PATH%" %*
  exit /b %ERRORLEVEL%
)

if not exist "%URLS_JSON%" (
  echo fireweave MCP launcher: missing %URLS_JSON%; cannot resolve MCPB URL 1>&2
  exit /b 1
)

if not exist "%BIN_DIR%" mkdir "%BIN_DIR%"

set "TMP_MCPB=%BIN_DIR%\.tmp.%RANDOM%.mcpb"

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "$j = Get-Content -Raw '%URLS_JSON%' | ConvertFrom-Json;" ^
  "$p = $j.platforms.'windows-x64';" ^
  "if (-not $p.url) { Write-Error 'no URL for windows-x64'; exit 1 };" ^
  "Write-Host 'fireweave MCP launcher: fetching binary (first launch, ~50-100MB)...' -ErrorAction Continue;" ^
  "Invoke-WebRequest -UseBasicParsing -Uri $p.url -OutFile '%TMP_MCPB%';" ^
  "$hash = (Get-FileHash -Algorithm SHA256 '%TMP_MCPB%').Hash.ToLower();" ^
  "if ($hash -ne $p.sha256.ToLower()) { Write-Error ('SHA-256 verification failed for ' + $p.url + ': expected ' + $p.sha256 + ', got ' + $hash); Remove-Item '%TMP_MCPB%' -ErrorAction SilentlyContinue; exit 1 };" ^
  "$zip = [System.IO.Compression.ZipFile]::OpenRead('%TMP_MCPB%');" ^
  "$entry = $zip.Entries | Where-Object { $_.FullName -eq 'server/%BIN_NAME%' };" ^
  "if (-not $entry) { Write-Error 'MCPB does not contain server/%BIN_NAME%'; $zip.Dispose(); Remove-Item '%TMP_MCPB%' -ErrorAction SilentlyContinue; exit 1 };" ^
  "[System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, '%BIN_PATH%', $true);" ^
  "$zip.Dispose();" ^
  "Remove-Item '%TMP_MCPB%' -ErrorAction SilentlyContinue;"

if not "%ERRORLEVEL%"=="0" (
  echo fireweave MCP launcher: setup failed. Are you online? Check above messages. 1>&2
  exit /b %ERRORLEVEL%
)

"%BIN_PATH%" %*
exit /b %ERRORLEVEL%
