"""fw_harness.py — scaffolded by ``/fireweave:initialise`` (PYTHON surface).

The "promote, not wrap" harness (D26): BOTH branches are present and the RUNNING
ENVIRONMENT — resolved by NAME, not a bare boolean — selects which one is live,
via ``FW_ENV_PROFILES``.
  dev  -> FireWeave local provider + OTel console exporter
  prod -> FireWeave remote provider (fw-server ``/v1/flags/evaluate``)

Nothing is swapped at promotion — ``safe-rollout`` ramps via ``flag.control`` and
never mutates this file.

BOOT BEACON: still deferred on this surface. There is no python deploy SDK, so
there is nothing to send the stamp tree with. ``verify_prod_path`` reports that
as a NAMED SKIP — a recorded gap, never a pass — and the flag path above is
unaffected: flags and deploy attestation are independent.

``init_fw_harness()`` MUST be called as the FIRST statement in the app entrypoint
(top of ``__main__`` / the ASGI/WSGI app factory) so the provider + telemetry are
live before any flag read. It is SYNCHRONOUS — do not await it. ``is_prod()`` is
retained as the unknown-environment tier fallback and the token
``verify_prod_path`` greps for.
"""

from __future__ import annotations

import os
import warnings
from typing import Mapping

from openfeature import api

from .fw_providers import make_connected_vendor_provider, make_dev_provider
# Plain import — USED below (passed nowhere yet, but referenced) so the stamp
# tree is not stripped. The python deploy SDK (Phase 1b) will send these.
from .fw_tracker import FW_STAMPS

# Surface participation (surface-ID routing) — dev-only tracking on this branch.
# fw-server mints one ``sfc_<ULID>`` per surface and ``/fireweave:initialise``
# RECORDS it here (Step 3f, ``fw repo declare-surfaces``) -- never invent one; its
# ``stamps`` are THIS surface's ``FW_STAMPS``. The python deploy SDK (Phase 1b)
# will send ``FW_SURFACES`` on the boot beacon (alongside the deduped ``stamps``
# union). Tracked but NOT transmitted yet — no prod-path work on this branch.
FW_SURFACES: list[dict[str, object]] = [{"surface_id": "sfc_REPLACE_ON_INIT", "stamps": FW_STAMPS}]

# env -> tier profile — regenerated from FireWeave ``list_project_environments``.
# Keep in sync with ``.fireweave/project.json`` ``rolloutReady.environments``.
# ``FW_DEFAULT_ENV`` is the project's ``defaultEnvironment`` — the row used when
# nothing is set at runtime. ``/fireweave:initialise --reinit`` regenerates this.
FW_DEFAULT_ENV = "development"
FW_ENV_PROFILES: dict[str, str] = {
    "development": "dev",
    "staging": "prod",
    "production": "prod",
}


# ── Environment source — GENERATED by ``/fireweave:initialise`` ──────────────
# FireWeave reads THIS project's OWN environment signal — you do NOT need to add
# a FireWeave-specific ``FW_ENV``. ``/fireweave:initialise`` asks how this repo /
# CI determines its live environment and generates ``_read_env_signal`` below to
# read YOUR var (``APP_ENV`` / ``ENVIRONMENT`` / a framework setting / a platform
# var). ``FW_ENV`` is retained ONLY as an optional override. Regenerated on
# ``--reinit`` — edit through the skill, not by hand.
# fw:env-source
def _read_env_signal(env: Mapping[str, str]) -> str | None:
    # Default before init tailors it to your app/platform: common env vars, then
    # the optional FW_ENV override. ``/fireweave:initialise`` replaces the first
    # read per your answer.
    return env.get("APP_ENV") or env.get("ENVIRONMENT") or env.get("ENV") or env.get("FW_ENV")


# Map a raw signal value -> a FireWeave environment NAME (a key of
# FW_ENV_PROFILES). initialise fills this only when your values differ from the
# FireWeave names (e.g. {"prod": "production"}). Empty = identity mapping.
FW_ENV_ALIASES: dict[str, str] = {}
# ─────────────────────────────────────────────────────────────────────────────


def resolve_fw_env_name(env: Mapping[str, str]) -> str:
    """Resolve the running environment NAME from the project's own signal."""
    raw = (_read_env_signal(env) or FW_DEFAULT_ENV).strip()
    return FW_ENV_ALIASES.get(raw, raw)


def _resolve_fw_tier(env: Mapping[str, str]) -> str:
    return FW_ENV_PROFILES.get(resolve_fw_env_name(env), "")


def is_prod(env: Mapping[str, str] | None = None) -> bool:
    """Retained tier probe + the token ``verify_prod_path`` greps for."""
    env = os.environ if env is None else env
    return _resolve_fw_tier(env) == "prod"


_ready = False


def init_fw_harness() -> None:
    """Idempotent boot — call FIRST in the app entrypoint, before any flag read."""
    global _ready
    if _ready:
        return
    _ready = True

    env = os.environ
    fw_env_name = resolve_fw_env_name(env)
    profile = FW_ENV_PROFILES.get(fw_env_name)
    # Unknown environment is NOT silently folded into dev/prod — fall back to the
    # is_prod() tier probe and WARN so the operator adds an explicit profile row.
    prod = (profile == "prod") if profile is not None else is_prod(env)
    if profile is None:
        warnings.warn(
            f"[fireweave] environment '{fw_env_name}' has no FW_ENV_PROFILES entry; "
            f"classified as '{'prod' if prod else 'dev'}' via is_prod() fallback. "
            "Run /fireweave:initialise --reinit or add it to FW_ENV_PROFILES.",
            stacklevel=2,
        )

    # Flags: prod-tier -> connected vendor provider (reads THIS environment's
    # credentials from os.environ); dev-tier -> FireWeave local provider. Both
    # come from the same SDK and the same runtime, so the tiers cannot skew.
    api.set_provider(
        make_connected_vendor_provider() if prod else make_dev_provider()
    )

    # Telemetry: console on both tiers for now. Direct OTLP export lands with the
    # python deploy SDK; emitting a half-wired exporter would be worse than
    # console, because it looks configured and silently drops every span.
    _init_console_telemetry("fireweave-app")

    # Boot beacon: DEFERRED — there is no python deploy SDK to send it with.
    # The stamp tree and its per-surface participation are tracked here so the
    # anchors stay honest; verify_prod_path records the missing beacon as a
    # named skip rather than a pass.
    _ = FW_STAMPS
    _ = FW_SURFACES


def _init_console_telemetry(service_name: str) -> None:
    """DEV telemetry: OTel console span exporter (no vendor egress)."""
    from opentelemetry import trace
    from opentelemetry.sdk.resources import Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor

    provider = TracerProvider(resource=Resource.create({"service.name": service_name}))
    provider.add_span_processor(SimpleSpanProcessor(ConsoleSpanExporter()))
    trace.set_tracer_provider(provider)


def fw_flag(key: str, default: bool) -> bool:
    """Flag-eval facade. Call after ``init_fw_harness()``. Anchor each call site
    with ``# @fireweave-flag <key>``."""
    return api.get_client().get_boolean_value(key, default)
