#!/bin/sh
# Auto-generated by packages/fw-plugins/build/lib/pack-mcpb.ts.
#
# Fireweave MCP launcher — runs the matching native binary for the host
# (os, arch). If the binary isn't already present in `bin/`, this script
# fetches the per-OS MCPB from GitHub Releases (declared in urls.json),
# verifies SHA-256, unzips the matching arch's binary, caches it under
# `bin/`, then execs.
#
# Alongside the cached binary it writes `bin/<name>.sha`, recording the digest
# the bundle was expected to have. On later launches that stamp is compared
# against urls.json — a STRING compare of two recorded values, never a rehash
# of the ~100 MB binary — so a bundle republished at the same version, or
# rebuilt locally, is re-fetched instead of being shadowed forever by a stale
# cache. A binary with no stamp (installed before this, or hand-seeded) execs
# exactly as it always did.
#
# Customer-side prerequisite: `curl`, `unzip`, and `sha256sum` (or
# `shasum -a 256` on macOS) on PATH. All three ship with stock macOS
# and every mainstream Linux distro.
#
# See .aidocs/publish-plugins-versioning-spec.md §4.7 (Component G)
# and .aidocs/publish-plugins-component-g-followups-plan.md.

set -e

# Resolve this server's bundle dir. Hosts that can't guarantee a stable cwd/$0
# (codex/opencode/cline) pass FW_PLUGIN_ROOT = absolute path to this dir, written
# by `fw mcp install`. Otherwise self-locate via $0 (Claude/Cursor).
if [ -n "${FW_PLUGIN_ROOT:-}" ]; then
  DIR="$FW_PLUGIN_ROOT"
else
  DIR="$(cd "$(dirname "$0")" && pwd)"
fi
BIN_DIR="$DIR/bin"
URLS_JSON="$DIR/urls.json"

# ── Detect platform ──────────────────────────────────────────────────────
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$OS" in
  linux|darwin) ;;
  *)
    echo "fireweave MCP launcher: unsupported OS '$OS' (Unix launcher)" >&2
    exit 1
    ;;
esac

ARCH=$(uname -m)
case "$ARCH" in
  x86_64|amd64) ARCH=x64 ;;
  arm64|aarch64) ARCH=arm64 ;;
  *)
    echo "fireweave MCP launcher: unsupported architecture '$ARCH'" >&2
    exit 1
    ;;
esac

PLATFORM_KEY="${OS}-${ARCH}"
BIN_NAME="server-${PLATFORM_KEY}"
BIN_PATH="$BIN_DIR/$BIN_NAME"
STAMP_PATH="$BIN_PATH.sha"

# Tiny JSON extraction — no jq dep on customer machines. The urls.json shape
# is generated by tools/publish/inject-mcpb-urls.ts; we parse two fields per
# platform via grep+sed. If the schema ever grows, switch to a real parser.
#
# Defined before the fast path, which reads sha256 to detect a stale cache.
extract_field() {
  field="$1"
  python3 -c "
import json,sys
with open('$URLS_JSON') as f: data=json.load(f)
p=data.get('platforms',{}).get('$PLATFORM_KEY',{})
sys.stdout.write(p.get('$field',''))
" 2>/dev/null || \
  # Fallback if python3 isn't present — use grep+sed against the known schema.
  awk -v platform="$PLATFORM_KEY" -v field="$field" '
    BEGIN { in_pf=0 }
    $0 ~ "\"" platform "\"" { in_pf=1 }
    in_pf && $0 ~ "\"" field "\"" {
      match($0, "\"" field "\"[[:space:]]*:[[:space:]]*\"[^\"]*\"")
      s = substr($0, RSTART, RLENGTH)
      sub("\"" field "\"[[:space:]]*:[[:space:]]*\"", "", s)
      sub("\".*", "", s)
      print s
      exit
    }
    in_pf && /\}/ { in_pf=0 }
  ' "$URLS_JSON"
}

# ── Fast path: binary already cached ─────────────────────────────────────
# Cheap staleness check: compare the digest recorded when this binary was
# cached against the one urls.json expects now. Two short strings — no hashing
# of the binary on the hot path.
if [ -x "$BIN_PATH" ]; then
  if [ -f "$STAMP_PATH" ] && [ -f "$URLS_JSON" ]; then
    CACHED_SHA=$(cat "$STAMP_PATH" 2>/dev/null || echo "")
    WANTED_SHA=$(extract_field sha256 || echo "")
    # An unreadable/absent expected digest must NOT invalidate a working
    # binary — fall through to exec rather than forcing a needless re-fetch.
    if [ -n "$WANTED_SHA" ] && [ "$CACHED_SHA" != "$WANTED_SHA" ]; then
      echo "fireweave MCP launcher: cached binary is stale (bundle digest changed); re-fetching..." >&2
      rm -f "$BIN_PATH" "$STAMP_PATH"
    else
      exec "$BIN_PATH" "$@"
    fi
  else
    # No stamp: installed before stamping existed, or seeded by hand
    # (`dev:install --seed-bin`). Keep the original behaviour exactly.
    exec "$BIN_PATH" "$@"
  fi
fi

# ── First-launch path: fetch + verify + extract ──────────────────────────
if [ ! -f "$URLS_JSON" ]; then
  echo "fireweave MCP launcher: missing $URLS_JSON; cannot resolve MCPB URL" >&2
  exit 1
fi

URL=$(extract_field url)
EXPECTED_SHA=$(extract_field sha256)

if [ -z "$URL" ]; then
  echo "fireweave MCP launcher: no URL in $URLS_JSON for platform $PLATFORM_KEY" >&2
  exit 1
fi
if [ -z "$EXPECTED_SHA" ]; then
  echo "fireweave MCP launcher: no SHA-256 in $URLS_JSON for platform $PLATFORM_KEY" >&2
  exit 1
fi

mkdir -p "$BIN_DIR"
TMP_MCPB="$BIN_DIR/.tmp.$$.mcpb"

echo "fireweave MCP launcher: fetching binary (first launch, ~50-100MB)..." >&2
if ! curl -fsSL "$URL" -o "$TMP_MCPB"; then
  rm -f "$TMP_MCPB"
  echo "" >&2
  echo "fireweave MCP launcher: could not fetch binary from $URL" >&2
  echo "Are you online? Retry the request; first launch needs network." >&2
  exit 1
fi

# Compute SHA-256 with whichever tool is present.
if command -v sha256sum >/dev/null 2>&1; then
  ACTUAL_SHA=$(sha256sum "$TMP_MCPB" | awk '{print $1}')
elif command -v shasum >/dev/null 2>&1; then
  ACTUAL_SHA=$(shasum -a 256 "$TMP_MCPB" | awk '{print $1}')
else
  rm -f "$TMP_MCPB"
  echo "fireweave MCP launcher: neither sha256sum nor shasum is available; cannot verify integrity" >&2
  exit 1
fi

if [ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]; then
  rm -f "$TMP_MCPB"
  echo "fireweave MCP launcher: SHA-256 verification failed for $URL" >&2
  echo "  expected: $EXPECTED_SHA" >&2
  echo "  got:      $ACTUAL_SHA" >&2
  echo "The release asset may be corrupted or tampered." >&2
  exit 1
fi

# Extract the matching binary from the MCPB ZIP. The binary lives at
# server/server-<os>-<arch> inside the bundle. Use unzip's -j (junk paths)
# so we don't recreate the server/ subdirectory inside bin/.
if ! command -v unzip >/dev/null 2>&1; then
  rm -f "$TMP_MCPB"
  echo "fireweave MCP launcher: unzip is required to extract the MCPB bundle" >&2
  exit 1
fi

TMP_BIN="$BIN_DIR/.tmp.$$.$BIN_NAME"
if ! unzip -p "$TMP_MCPB" "server/$BIN_NAME" > "$TMP_BIN" 2>/dev/null; then
  rm -f "$TMP_MCPB" "$TMP_BIN"
  echo "fireweave MCP launcher: MCPB does not contain server/$BIN_NAME" >&2
  exit 1
fi
chmod +x "$TMP_BIN"

# Atomic rename (mv -n = no-clobber) handles concurrent first-launch race:
# both clients download to distinct .tmp paths; the loser of `mv -n` notices
# the binary now exists and re-execs.
if mv -n "$TMP_BIN" "$BIN_PATH" 2>/dev/null; then
  rm -f "$TMP_MCPB"
else
  rm -f "$TMP_MCPB" "$TMP_BIN"
  if [ ! -x "$BIN_PATH" ]; then
    echo "fireweave MCP launcher: another launcher won the race but binary still missing" >&2
    exit 1
  fi
fi

# Record the digest this binary was fetched for. Best-effort: a read-only bin/
# just means the next launch takes the no-stamp branch and execs as before.
printf '%s' "$EXPECTED_SHA" > "$STAMP_PATH" 2>/dev/null || true

# macOS Gatekeeper: a binary extracted from a downloaded archive can carry the
# com.apple.quarantine xattr, which blocks exec. Clear it (best-effort).
if [ "$OS" = "darwin" ] && command -v xattr >/dev/null 2>&1; then
  xattr -d com.apple.quarantine "$BIN_PATH" 2>/dev/null || true
fi

exec "$BIN_PATH" "$@"
